### ISSUE TITLE
Depricate in favour of SavitzkyGolay.jl?

### ISSUE THREAD

**Issue by KronosTheLate** [Klafyvel/SavitskyGolayFilters.jl#4]
This package seems not so actively maintained, and also somewhat less capable than https://github.com/lnacquaroli/SavitzkyGolay.jl.

Unless this package can do something that the other can not, I suggest starting the readme with something like "This package is depricated. For a more capable implementation of Savitzky-Golay filtering in Julia, see [SavitzkyGolay.jl](https://github.com/lnacquaroli/SavitzkyGolay.jl).

**Comment by Klafyvel** [comment]
Hi. Yes, indeed, SavitzkyGolay.jl is adding more functionalities. Furthermore, I'm not using this package anymore. Thanks for bringing that up.
